DATADB:
    MYSQL:
        HOST: 47.98.56.206
        UNAME: root
        PWD: 123456
        DNAME: llf

QUEUES:
    KAFKA:
#        HOST: ['47.75.33.177:9092','47.75.176.97:9092','47.75.170.254:9092']
#        topic: blz-rate-prod
        HOST: 47.75.116.175:9092
        TOPIC: blz-rate-test